### ISSUE TITLE
Byte Order Marks

### ISSUE THREAD

**Issue by JalonSolov** [nedpals/jisoni#1]
The first 4 tests fail because you're not checking for BOM, Byte Order Mark, in the JSON.

This is invalid according to the JSON spec, but it is also something you are allowed to ignore if it is there.

The first 3 tests should always fail, but it would be good to say why - they are not UTF-8.  Only UTF-8 is valid for JSON.

This page has a fairly complete set of BOMs and the hex codes that represent them:

https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by JalonSolov** [comment]
The relevant part of the JSON spec, RFC 8259:

"8.1.  Character Encoding

   JSON text exchanged between systems that are not part of a closed
   ecosystem MUST be encoded using UTF-8 [RFC3629].

   Previous specifications of JSON have not required the use of UTF-8
   when transmitting JSON text.  However, the vast majority of JSON-
   based software implementations have chosen to use the UTF-8 encoding,
   to the extent that it is the only encoding that achieves
   interoperability.

   Implementations MUST NOT add a byte order mark (U+FEFF) to the
   beginning of a networked-transmitted JSON text.  In the interests of
   interoperability, implementations that parse JSON texts MAY ignore
   the presence of a byte order mark rather than treating it as an
   error."

**Comment by nedpals** [comment]
i added bom-checking when creating a new instance of the parser. supporting other encoding format is an another issue that will be discussed in the future.
