### ISSUE TITLE
Need more details in error messages

### ISSUE THREAD

**Issue by JalonSolov** [nedpals/jisoni#4]
Trying some of the JSONTestSuite files individually, I see error messages like
```
json: number not allowed
```
and that's all.  No indication of which line in the file (I know these little tests are only one line, but it will make a huge difference in multi-line files), no explanation for why it isn't allowed, etc.

**Comment by nedpals** [comment]
i haven't improved the error messages even in the new rewrite yet but ill find a way to make it meaningful

**Comment by nedpals** [comment]
Error messages are now informative than before. Added location of the error.
![image](https://user-images.githubusercontent.com/7358345/85108450-53b24880-b242-11ea-84f2-d022ea28cbe3.png)

**Comment by JalonSolov** [comment]
Nice!  Very informative, now, and pinpoints exact problem location.
